// Entity registry: drives the generic CRUD router, access control and the OpenAPI spec.
//
// Access model:
//   STAFF  = security | facility_admin | park_admin | super_admin
//   ADMIN  = facility_admin | park_admin | super_admin
//   SUPER  = super_admin
//   OWNER  = vehicle_owner (restricted to records matching ownerField)
//
// facilityScoped: non-super staff with an assigned_facility_id only see rows of
// their facility. ownerField: vehicle_owner access is restricted to rows whose
// ownerField equals their email.

const STAFF = ['security', 'facility_admin', 'park_admin', 'super_admin'];
const ADMIN = ['facility_admin', 'park_admin', 'super_admin'];
const SUPER = ['super_admin'];
const ALL = [...STAFF, 'vehicle_owner'];

const entities = {
  Facility: {
    model: 'facility',
    read: ALL,
    write: SUPER,
    facilityScoped: false,
    fields: {
      name: { type: 'string', required: true },
      address: { type: 'string' },
      city: { type: 'string' },
      capacity: { type: 'number' },
      billing_mode: { type: 'string', enum: ['free', 'standard', 'hourly'] },
      hourly_rate: { type: 'number' },
      standard_rate: { type: 'number' },
      subscription_monthly_fee: { type: 'number' },
      currency: { type: 'string' },
      exit_timeout_minutes: { type: 'number' },
      qr_deactivate_after_days: { type: 'number' },
      status: { type: 'string', enum: ['active', 'inactive'] },
      logo_url: { type: 'string' },
      contact_phone: { type: 'string' },
      contact_email: { type: 'string' },
    },
  },
  Vehicle: {
    model: 'vehicle',
    read: ALL,
    write: ALL, // owners may create/update their own vehicles; enforced via ownerField
    facilityScoped: true,
    ownerField: 'owner_email',
    dateFields: ['guest_pass_expires', 'last_entry', 'last_exit', 'qr_request_date'],
    fields: {
      qr_code_id: { type: 'string' },
      owner_name: { type: 'string' },
      owner_phone: { type: 'string' },
      owner_email: { type: 'string' },
      owner_photo_url: { type: 'string' },
      driver_name: { type: 'string' },
      driver_phone: { type: 'string' },
      plate_number: { type: 'string', required: true },
      make_model: { type: 'string' },
      color: { type: 'string' },
      photo_front_url: { type: 'string' },
      photo_back_url: { type: 'string' },
      photo_side_url: { type: 'string' },
      photo_url: { type: 'string' },
      facility_id: { type: 'string' },
      status: { type: 'string', enum: ['active', 'blacklisted', 'suspended'] },
      registration_type: { type: 'string', enum: ['permanent', 'guest'] },
      guest_pass_expires: { type: 'string', format: 'date-time' },
      guest_pass_notified: { type: 'boolean' },
      is_inside: { type: 'boolean' },
      last_entry: { type: 'string', format: 'date-time' },
      last_exit: { type: 'string', format: 'date-time' },
      registered: { type: 'boolean' },
      qr_requested: { type: 'boolean' },
      qr_request_date: { type: 'string', format: 'date-time' },
      notes: { type: 'string' },
    },
  },
  QRCode: {
    model: 'qRCode',
    read: STAFF,
    write: STAFF,
    facilityScoped: true,
    fields: {
      code_id: { type: 'string', required: true },
      facility_id: { type: 'string', required: true },
      batch_name: { type: 'string' },
      code_type: { type: 'string', enum: ['permanent', 'guest'] },
      guest_duration_hours: { type: 'number' },
      status: { type: 'string', enum: ['available', 'assigned', 'deactivated'] },
      vehicle_id: { type: 'string' },
      generated_by: { type: 'string' },
      qr_image_url: { type: 'string' },
    },
  },
  ScanLog: {
    model: 'scanLog',
    read: ALL,
    write: STAFF,
    facilityScoped: true,
    ownerVia: 'vehicle', // vehicle_owner reads scans of vehicles they own
    dateFields: ['timestamp'],
    fields: {
      vehicle_id: { type: 'string' },
      qr_code_id: { type: 'string', required: true },
      facility_id: { type: 'string' },
      scan_type: { type: 'string', enum: ['entry', 'exit'], required: true },
      scanned_by: { type: 'string' },
      scanned_by_name: { type: 'string' },
      plate_number: { type: 'string' },
      owner_name: { type: 'string' },
      driver_name: { type: 'string' },
      driver_phone: { type: 'string' },
      timestamp: { type: 'string', format: 'date-time' },
      status: { type: 'string', enum: ['completed', 'pending_approval', 'denied', 'timeout'] },
      items_declared: { type: 'array' },
      booth_photo_urls: { type: 'array' },
      security_confirmed: { type: 'boolean' },
      security_notes: { type: 'string' },
      discrepancies: { type: 'string' },
      notes: { type: 'string' },
    },
  },
  ItemLog: {
    model: 'itemLog',
    read: STAFF,
    write: STAFF,
    facilityScoped: true,
    fields: {
      scan_log_id: { type: 'string' },
      vehicle_id: { type: 'string', required: true },
      facility_id: { type: 'string' },
      plate_number: { type: 'string' },
      owner_name: { type: 'string' },
      driver_name: { type: 'string' },
      scan_type: { type: 'string', enum: ['entry', 'exit'], required: true },
      item_name: { type: 'string', required: true },
      quantity: { type: 'number' },
      description: { type: 'string' },
      photo_urls: { type: 'array' },
      verified_on_exit: { type: 'boolean' },
      discrepancy_note: { type: 'string' },
      logged_by: { type: 'string' },
    },
  },
  ExitRequest: {
    model: 'exitRequest',
    read: ALL,
    write: STAFF,
    facilityScoped: true,
    ownerField: 'owner_email',
    dateFields: ['responded_at'],
    fields: {
      vehicle_id: { type: 'string', required: true },
      qr_code_id: { type: 'string' },
      facility_id: { type: 'string', required: true },
      owner_name: { type: 'string' },
      owner_phone: { type: 'string' },
      owner_email: { type: 'string' },
      plate_number: { type: 'string' },
      requested_by: { type: 'string' },
      status: { type: 'string', enum: ['pending', 'approved', 'rejected', 'timeout', 'escalated'] },
      responded_at: { type: 'string', format: 'date-time' },
      responded_by: { type: 'string' },
      approval_token: { type: 'string' },
      billing_amount: { type: 'number' },
      duration_minutes: { type: 'number' },
      notes: { type: 'string' },
    },
  },
  DriverPass: {
    model: 'driverPass',
    read: ALL,
    write: ALL,
    facilityScoped: false,
    ownerField: 'owner_email',
    dateFields: ['expires_at', 'last_used_at'],
    fields: {
      vehicle_id: { type: 'string', required: true },
      owner_id: { type: 'string' },
      owner_email: { type: 'string' },
      plate_number: { type: 'string' },
      driver_name: { type: 'string' },
      driver_phone: { type: 'string' },
      pass_code: { type: 'string', required: true },
      expires_at: { type: 'string', format: 'date-time' },
      status: { type: 'string', enum: ['active', 'expired', 'deactivated'] },
      notes: { type: 'string' },
      last_used_at: { type: 'string', format: 'date-time' },
      use_count: { type: 'number' },
    },
  },
  Payment: {
    model: 'payment',
    read: ALL,
    write: STAFF,
    facilityScoped: true,
    ownerVia: 'vehicle', // vehicle_owner reads payments for vehicles they own
    dateFields: ['paid_at'],
    fields: {
      vehicle_id: { type: 'string' },
      facility_id: { type: 'string', required: true },
      exit_request_id: { type: 'string' },
      amount: { type: 'number', required: true },
      currency: { type: 'string' },
      billing_mode: { type: 'string', enum: ['free', 'standard', 'hourly'] },
      duration_minutes: { type: 'number' },
      status: { type: 'string', enum: ['pending', 'paid', 'failed', 'waived'] },
      payment_method: { type: 'string' },
      reference: { type: 'string' },
      plate_number: { type: 'string' },
      owner_name: { type: 'string' },
      paid_at: { type: 'string', format: 'date-time' },
    },
  },
  SubscriptionPayment: {
    model: 'subscriptionPayment',
    read: STAFF,
    write: STAFF,
    facilityScoped: true,
    dateFields: ['paid_at'],
    fields: {
      facility_id: { type: 'string', required: true },
      facility_name: { type: 'string' },
      amount: { type: 'number', required: true },
      month: { type: 'number', required: true },
      year: { type: 'number', required: true },
      status: { type: 'string', enum: ['pending', 'paid', 'failed', 'waived'] },
      paystack_reference: { type: 'string' },
      paid_at: { type: 'string', format: 'date-time' },
      email: { type: 'string' },
      created_by: { type: 'string' },
      notes: { type: 'string' },
    },
  },
  BillingItem: {
    model: 'billingItem',
    read: STAFF,
    write: ADMIN,
    facilityScoped: true,
    fields: {
      name: { type: 'string', required: true },
      description: { type: 'string' },
      amount: { type: 'number', required: true },
      category: { type: 'string', enum: ['app_launch', 'registration', 'subscription', 'parking', 'penalty', 'maintenance', 'other'] },
      facility_id: { type: 'string' },
      is_active: { type: 'boolean' },
      currency: { type: 'string' },
    },
  },
  UserBill: {
    model: 'userBill',
    read: ALL,
    write: ADMIN,
    facilityScoped: true,
    ownerField: 'owner_email',
    dateFields: ['due_date', 'paid_at'],
    fields: {
      billing_item_id: { type: 'string' },
      vehicle_id: { type: 'string' },
      facility_id: { type: 'string', required: true },
      owner_name: { type: 'string' },
      owner_email: { type: 'string' },
      plate_number: { type: 'string' },
      title: { type: 'string', required: true },
      description: { type: 'string' },
      category: { type: 'string', enum: ['app_launch', 'registration', 'subscription', 'parking', 'penalty', 'maintenance', 'other'] },
      amount: { type: 'number', required: true },
      currency: { type: 'string' },
      status: { type: 'string', enum: ['pending', 'paid', 'waived', 'overdue'] },
      due_date: { type: 'string', format: 'date-time' },
      billing_month: { type: 'number' },
      billing_year: { type: 'number' },
      payment_method: { type: 'string' },
      paystack_reference: { type: 'string' },
      paid_at: { type: 'string', format: 'date-time' },
      issued_by: { type: 'string' },
      notes: { type: 'string' },
    },
  },
  SecurityAlert: {
    model: 'securityAlert',
    read: STAFF,
    write: STAFF,
    facilityScoped: true,
    dateFields: ['resolved_at'],
    fields: {
      alert_type: { type: 'string', enum: ['item_discrepancy', 'overstay', 'blacklist_attempt', 'multiple_entry', 'guest_pass_expired'], required: true },
      severity: { type: 'string', enum: ['low', 'medium', 'high', 'critical'], required: true },
      status: { type: 'string', enum: ['open', 'investigating', 'resolved', 'dismissed'] },
      facility_id: { type: 'string' },
      facility_name: { type: 'string' },
      vehicle_id: { type: 'string' },
      plate_number: { type: 'string' },
      owner_name: { type: 'string' },
      driver_name: { type: 'string' },
      scan_log_id: { type: 'string' },
      title: { type: 'string' },
      description: { type: 'string' },
      discrepancy_details: { type: 'string' },
      overstay_hours: { type: 'number' },
      threshold_hours: { type: 'number' },
      resolved_by: { type: 'string' },
      resolved_at: { type: 'string', format: 'date-time' },
      resolution_notes: { type: 'string' },
      notified: { type: 'boolean' },
    },
  },
  ShiftHandover: {
    model: 'shiftHandover',
    read: STAFF,
    write: STAFF,
    facilityScoped: true,
    dateFields: ['shift_start', 'shift_end'],
    fields: {
      officer_name: { type: 'string', required: true },
      officer_email: { type: 'string' },
      facility_id: { type: 'string', required: true },
      facility_name: { type: 'string' },
      shift_start: { type: 'string', format: 'date-time' },
      shift_end: { type: 'string', format: 'date-time' },
      total_entries: { type: 'number' },
      total_exits: { type: 'number' },
      vehicles_inside: { type: 'number' },
      pending_exits: { type: 'number' },
      notes: { type: 'string' },
      next_officer_name: { type: 'string' },
      next_officer_email: { type: 'string' },
      status: { type: 'string', enum: ['draft', 'sent'] },
      report_data: { type: 'object' },
    },
  },
  NotificationSettings: {
    model: 'notificationSettings',
    read: ALL,
    write: ALL,
    facilityScoped: false,
    ownerField: 'user_email',
    fields: {
      facility_id: { type: 'string' },
      user_id: { type: 'string' },
      user_email: { type: 'string' },
      notify_email: { type: 'boolean' },
      notify_inapp: { type: 'boolean' },
      notify_whatsapp: { type: 'boolean' },
      whatsapp_number: { type: 'string' },
      notify_on_entry: { type: 'boolean' },
      notify_on_exit_request: { type: 'boolean' },
      notify_on_guest_expiry: { type: 'boolean' },
      notify_on_blacklist: { type: 'boolean' },
      security_override_enabled: { type: 'boolean' },
      security_override_roles: { type: 'array' },
      guest_pass_alert_minutes: { type: 'number' },
    },
  },
  LegalDocument: {
    model: 'legalDocument',
    read: 'public',
    write: SUPER,
    facilityScoped: false,
    fields: {
      document_type: { type: 'string', enum: ['privacy_policy', 'terms_of_service'], required: true },
      title: { type: 'string', required: true },
      content: { type: 'string', required: true },
      version: { type: 'string' },
      is_active: { type: 'boolean' },
      updated_by: { type: 'string' },
      notes: { type: 'string' },
    },
  },
  AppConfig: {
    model: 'appConfig',
    read: ALL,
    write: SUPER,
    facilityScoped: false,
    fields: {
      key: { type: 'string', required: true },
      value: { type: 'string' },
      value_json: { type: 'object' },
      label: { type: 'string' },
      description: { type: 'string' },
      category: { type: 'string', enum: ['general', 'security', 'alerts', 'billing', 'notifications', 'features'] },
      updated_by: { type: 'string' },
    },
  },
};

module.exports = { entities, STAFF, ADMIN, SUPER, ALL };
